name: Instagram AI Agent

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-instagram-agent:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      INSTAGRAM_CREDENTIALS_JSON: ${{ secrets.INSTAGRAM_CREDENTIALS_JSON }}
      DOTENV_FILE: ${{ secrets.DOTENV_FILE }}
      INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd 'insagram ai agent'
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore credentials.json from secret
        run: |
          mkdir -p 'insagram ai agent'
          echo "$GOOGLE_CREDENTIALS_JSON" > 'insagram ai agent/credentials.json'

      - name: Restore instagram_credentials.json from secret
        run: |
          mkdir -p 'insagram ai agent'
          echo "$INSTAGRAM_CREDENTIALS_JSON" > 'insagram ai agent/instagram_credentials.json'

      - name: Restore .env from secret
        run: |
          mkdir -p 'insagram ai agent'
          echo "$DOTENV_FILE" > 'insagram ai agent/.env'

      - name: Run Instagram AI Agent
        run: |
          cd 'insagram ai agent'
          python main.py
