name: Instagram AI Agent

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-instagram-agent:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      INSTAGRAM_CREDENTIALS_JSON: ${{ secrets.INSTAGRAM_CREDENTIALS_JSON }}
      DOTENV_FILE: ${{ secrets.DOTENV_FILE }}
      INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
      OAUTH_CLIENT_SECRET_JSON: ${{ secrets.OAUTH_CLIENT_SECRET_JSON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore credentials.json from secret
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json

      - name: Restore instagram_credentials.json from secret
        run: |
          echo "$INSTAGRAM_CREDENTIALS_JSON" > instagram_credentials.json

      - name: Restore .env from secret
        run: |
          echo "$DOTENV_FILE" > .env

      - name: Restore OAuth client secret from secret
        run: |
          echo "$OAUTH_CLIENT_SECRET_JSON" > client_secret_260892241319-4m6pavuqufep653d9ucvmnt2e6gm95ad.apps.googleusercontent.com.json

      - name: Run Instagram AI Agent
        run: python main.py
